name: Documentation
description: Report issues or suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: textarea
    id: description
    attributes:
      label: Documentation Issue
      description: What needs to be documented or improved?
      placeholder: Describe the documentation issue or improvement
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation? (README, wiki, code comments, etc.)
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should we improve this documentation?
      placeholder: Your suggestions for improvement

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
